pins.servoSetPulse(AnalogPin.P1, 1500)
pins.servoSetPulse(AnalogPin.P2, 1500)
pins.servoWritePin(AnalogPin.P1, 0)
pins.servoWritePin(AnalogPin.P2, 0)
basic.forever(function () {
    pins.servoWritePin(AnalogPin.P1, 30)
    pins.servoWritePin(AnalogPin.P2, 30)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P1, 170)
    pins.servoWritePin(AnalogPin.P2, 170)
    basic.pause(500)
})
